
package hr.apis_it.fin._2012.services.fiskalizacijaservice;


import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FiskalizacijaService", targetNamespace = "http://www.apis-it.hr/fin/2012/services/FiskalizacijaService", wsdlLocation = "classpath:wsdl/FiskalizacijaServiceTest.wsdl")
public class FiskalizacijaService
    extends Service
{

    private final static URL FISKALIZACIJASERVICE_WSDL_LOCATION;
    private final static WebServiceException FISKALIZACIJASERVICE_EXCEPTION;
    private final static QName FISKALIZACIJASERVICE_QNAME = new QName("http://www.apis-it.hr/fin/2012/services/FiskalizacijaService", "FiskalizacijaService");

    static {
        WebServiceException e = null;
        URL url = null;
		try {
			url = new URL(new URL("file:"), "./wsdl/FiskalizacijaServiceTest.wsdl");	        
		} catch (MalformedURLException e1) {
			e1.printStackTrace();
		}
        FISKALIZACIJASERVICE_WSDL_LOCATION = url;
        FISKALIZACIJASERVICE_EXCEPTION = e;
    }

    public FiskalizacijaService() {
        super(__getWsdlLocation(), FISKALIZACIJASERVICE_QNAME);
    }

    public FiskalizacijaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FISKALIZACIJASERVICE_QNAME, features);
    }

    public FiskalizacijaService(URL wsdlLocation) {
        super(wsdlLocation, FISKALIZACIJASERVICE_QNAME);
    }

    public FiskalizacijaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FISKALIZACIJASERVICE_QNAME, features);
    }

    public FiskalizacijaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FiskalizacijaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FiskalizacijaPortType
     */
    @WebEndpoint(name = "FiskalizacijaPortType")
    public FiskalizacijaPortType getFiskalizacijaPortType() {
        return super.getPort(new QName("http://www.apis-it.hr/fin/2012/services/FiskalizacijaService", "FiskalizacijaPortType"), FiskalizacijaPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FiskalizacijaPortType
     */
    @WebEndpoint(name = "FiskalizacijaPortType")
    public FiskalizacijaPortType getFiskalizacijaPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.apis-it.hr/fin/2012/services/FiskalizacijaService", "FiskalizacijaPortType"), FiskalizacijaPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FISKALIZACIJASERVICE_EXCEPTION!= null) {
            throw FISKALIZACIJASERVICE_EXCEPTION;
        }
        return FISKALIZACIJASERVICE_WSDL_LOCATION;
    }

}
